# permissions for end users to edit vpcendpointservices.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: vpcendpointservice-editor-role
rules:
- apiGroups:
  - vpc-endpoint-service.fil.com
  resources:
  - vpcendpointservices
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - vpc-endpoint-service.fil.com
  resources:
  - vpcendpointservices/status
  verbs:
  - get
